### ISSUE TITLE
No 'Access-Control-Allow-Origin', CORS problem

### ISSUE THREAD

**Issue by tristantbg** [meilisearch/meilisearch-digital-ocean#60] opened 2020-10-31 10:16 UTC
While trying to query a search on a Meilisearch Droplet using a Nuxt app in production and using the meilisearch-javascript package I get this error :

`No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

How can I set headers to the Meilisearch droplet to avoid this error ?

(the domain has been set with SSL and search is working properly)

Many thanks for your help !

**Comment by eskombro** [comment] 2020-10-31 20:57
Hi @tristantbg !

Can you confirm if this is related to https://github.com/meilisearch/MeiliSearch/issues/1021 ? 

If it is, it is a MeilISearch reported bug (not related to DigitalOcean deployment) but migth be indeed a missing API KEY. If you have any additional information or steps to reproduce your problem, it would be very much appreciated !

**Comment by eskombro** [comment] 2020-10-31 20:58
Hi @tristantbg !

Can you confirm if this is related to https://github.com/meilisearch/MeiliSearch/issues/1021 ? 

If it is, it is a MeilISearch reported bug (not related to DigitalOcean deployment). If you have any additional information or steps to reproduce your problem, it would be very much appreciated !

Do not hesitate to follow the discussion on that issue! Thanks!

**Comment by tristantbg** [comment] 2020-10-31 21:04
Hi @eskombro !

Yes I guess this is the same problem :) 
If you already fixed it, I just need to update my Meilisearch to the latest release to solve this problem ?

Many thanks for your quick answer !

**Comment by eskombro** [comment] 2020-10-31 23:13
@tristantbg are you sending your search reques using your public API KEY?

**Comment by tristantbg** [comment] 2020-11-01 09:54
> @tristantbg are you sending your search request using your public API KEY?

No, I am using the **private_key** one.

**Comment by eskombro** [comment] 2020-11-02 11:08
@tristantbg could you please post your problem with the code or an example on how to reproduce on this issue: https://github.com/meilisearch/MeiliSearch/issues/1021?

I am closing this issue because it is not related to DigitalOcean and this problem is being discussed there :)

**Closed by eskombro** 2020-11-02 11:08 UTC
